apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-deployment
  labels:
    app: devops-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-python
  template:
    metadata:
      labels:
        app: devops-python
    spec:
      containers:
        - name: devops-python-container
          image: hack4u2/devsu-demo-devops-python:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "Fi5tb5y-4iW01m7-x6lUqL6G-XLKFDz66cu-fXEZ3_A5AJPvtM9Wb1JjbWSQCGeo6I"
            - name: DATABASE_NAME
              value: "devsub"
            - name: ALLOWED_HOSTS
              value: "localhost,127.0.0.1,0.0.0.0,192.168.49.2,devops.internal"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
