apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-deployment
  namespace: django-namespace
  labels:
    app: devops-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-python
  template:
    metadata:
      labels:
        app: devops-python
    spec: 
      containers:
        - name: devops-python-container
          image: hack4u2/devsu-demo-devops-python:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              value: "Fi5tb5y-4iW01m7-x6lUqL6G-XLKFDz66cu-fXEZ3_A5AJPvtM9Wb1JjbWSQCGeo6I"
            - name: DATABASE_NAME
              value: "db.sqlite3"
            - name: ALLOWED_HOSTS
              value: "localhost,127.0.0.1,0.0.0.0,35.224.122.238"
          command: ["sh", "-c"]
          args:
            - python manage.py migrate --noinput && gunicorn demo.wsgi:application --bind 0.0.0.0:${PORT}
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          volumeMounts: 
            - name: django-persistent-storage
              mountPath: /app
      volumes: 
        - name: django-persistent-storage
          persistentVolumeClaim:
            claimName: django-db-pvc
