apiVersion: v1
kind: Service
metadata:
  name: devops-python-svc
  namespace: django-namespace
spec:
  type: NodePort
  selector:
    app: devops-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007  
