apiVersion: v1
kind: Service
metadata:
  name: devops-python-service
  namespace: django-namespace
spec:
  type: LoadBalancer
  selector:
    app: devops-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
